# Generated by Django 3.2.8 on 2021-11-16 08:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='postedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=50)),
                ('jobPos', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=50)),
                ('timing', models.CharField(max_length=50)),
                ('reqSkill', models.TextField(blank=True)),
                ('expLevel', models.CharField(max_length=50)),
                ('postedBy', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('appliedPeople', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('userName', models.CharField(max_length=100, unique=True)),
                ('compName', models.CharField(blank=True, max_length=50)),
                ('firstName', models.CharField(blank=True, max_length=50)),
                ('lastName', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(max_length=70, unique=True)),
                ('signUpDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_recruiter', models.BooleanField(default=False)),
                ('countryCode', models.CharField(blank=True, max_length=5)),
                ('contactNumber', models.CharField(blank=True, max_length=10)),
                ('dob', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('bio', models.CharField(blank=True, max_length=300)),
                ('skills', models.TextField(blank=True, default='')),
                ('projects', models.TextField(blank=True, default='')),
                ('linkGithub', models.URLField(blank=True)),
                ('linkLinkedIn', models.URLField(blank=True)),
                ('linkExtra', models.TextField(blank=True, default='')),
                ('appliedJobsTo', models.TextField(blank=True, default='')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
