# Generated by Django 3.2.8 on 2021-11-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postedjob',
            name='desc',
            field=models.CharField(max_length=300),
        ),
    ]
