export {LandingPage} from './landingpage/LandingPage';
export {LoginPage} from './login-register-pages/LoginPage'
export {RegisterPage} from './login-register-pages/RegisterPage'
export {JobsPage} from './jobspage/JobsPage'
export {UserProfilePage} from './userprofilepage/UserProfilePage';
export {PostingJobDetails} from './posting-job-details/PostingJobDetails';
export {PostedJobsPage} from './jobspage/PostedJobsPage'
export {AppliedJobsPage} from './jobspage/AppliedJobsPage'
export {JobViewPage} from './jobspage/JobViewPage'